version: "3"
services:
  app:
    container_name: app
    build: .
    command: sh -c "python -m app"
    depends_on:
      - hub

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
      - "7900:7900"

  hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
